version: '3.9'
services:
  mqtt:
    image: emqx/nanomq
    container_name: nanomq
    network_mode: host
    environment:
      TZ: "{{ timezone }}"
    volumes:
      - './etc/nanomq.conf:/etc/nanomq.conf:ro'
      - './etc/nanomq_acl.conf:/etc/nanomq_acl.conf:ro'
      - './etc/nanomq_pwd.conf:/etc/nanomq_pwd.conf:ro'
      - './data:/tmp'
    restart: unless-stopped
