---
- name: Stopping old container
  docker_container:
    name: influx2
    image: influxdb:latest
    state: absent
  tags:
    - influx2

- name: Removing old directories
  file:
    path: /docker-data/influx2
    state: absent
  tags:
    - influx2

- name: Removing old directories
  file:
    path: /data/influx2
    state: absent
  tags:
    - influx2

- name: Creating directories to deploy
  file:
    path: /docker-data/influx2/config
    state: directory
    owner: 1000
    group: 1000
  tags:
    - influx2

- name: Creating directories for data
  file:
    path: /data/influx2
    state: directory
    owner: 1000
    group: 1000
  tags:
    - influx2

- name: Setup
  docker_container:
    name: influx2_setup
    image: influxdb:latest
    detach: false
    recreate: false
    auto_remove: true
    volumes: 
      - /data/influx2:/var/lib/influxdb2
      - ./config:/etc/influxdb2
    env:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME={{ docker_influxdb_init_username }}
      - DOCKER_INFLUXDB_INIT_PASSWORD={{ docker_influxdb_init_password }}
      - DOCKER_INFLUXDB_INIT_ORG={{ docker_influxdb_init_org }}
      - DOCKER_INFLUXDB_INIT_BUCKET={{ docker_influxdb_init_bucket }}
      - DOCKER_INFLUXDB_RETENTION={{ docker_influxdb_retention }}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN={{ docker_influxdb_init_admin_token }}
  tags:
    - influx2

- name: Copying docker-compose
  template:
    src: docker-compose.yml
    dest: /docker-data/influx2/docker-compose.yml
    mode: '0644'
  tags:
    - influx2

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/influx2
    build: no
    pull: yes
  tags:
    - influx2

