---
- name: Stopping old container
  docker_container:
    name: influx2
    image: influxdb:latest
    state: absent
  tags:
    - influx2

- name: Stopping old container
  docker_container:
    name: influx2_setup
    image: influxdb:latest
    state: absent
  tags:
    - influx2

- name: Removing old directories
  file:
    path: /docker-data/influx2
    state: absent
  tags:
    - influx2

- name: Removing old directories
  file:
    path: "{{ data_path }}"
    state: absent
  tags:
    - influx2

- name: Creating directories to deploy
  file:
    path: /docker-data/influx2/config
    state: directory
    owner: 1000
    group: 1000
  tags:
    - influx2

- name: Creating directories for data
  file:
    path: "{{ data_path }}"
    state: directory
    owner: 1000
    group: 1000
  tags:
    - influx2

# Not using docker-compose setup env variable because it fails, workaround for not using 
# provieded script.
# Following the manual steps for generating initial setup and configuration.

- name: Setup 1/2
  shell: |
    docker run -d \
      --name influx2_setup \
      -v /data/influx2:/var/lib/influxdb2 \
      -v /docker-data/influx2/config:/etc/influxdb2 \
      influxdb
  tags:
    - influx2

- name: Pause for 5 seconds
  pause:
    seconds: 5

- name: Setup 2/2
  shell: |
    docker exec influx2_setup \
      influx setup \
        --username '{{ docker_influxdb_init_username }}' \
        --password '{{ docker_influxdb_init_password }}' \
        --org '{{ docker_influxdb_init_org }}' \
        --bucket '{{ docker_influxdb_init_bucket }}' \
        --retention '{{ docker_influxdb_retention }}' \
        --token  '{{ docker_influxdb_init_admin_token }}' \
        -f
  tags:
    - influx2

- name: Creating config file
  shell: docker exec influx2_setup influx server-config > /docker-data/influx2/config/influxdb.conf
  tags:
    - influx2

- name: Stopping setup container
  docker_container:
    name: influx2_setup
    image: influxdb:latest
    state: absent
  tags:
    - influx2

- name: Copying docker-compose
  template:
    src: docker-compose.yml
    dest: /docker-data/influx2/docker-compose.yml
    mode: '0644'
  tags:
    - influx2

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/influx2
    build: no
    pull: yes
  tags:
    - influx2
