version: '3.8'
services:
  influx2:
    container_name: influx2
    image: influxdb:latest
    restart: unless-stopped
    volumes:
      - "{{ data_path }}:/var/lib/influxdb2"
      - ./config:/etc/influxdb2
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ="{{ timezone }}"
      #- DOCKER_INFLUXDB_INIT_MODE=setup
      #- DOCKER_INFLUXDB_INIT_USERNAME=admin
      #- 'DOCKER_INFLUXDB_INIT_PASSWORD=XYZ'
      #- DOCKER_INFLUXDB_INIT_ORG=i40sys
      #- DOCKER_INFLUXDB_INIT_BUCKET=iiot
      #- DOCKER_INFLUXDB_RETENTION=1w
      #- 'DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=q_XYZDwJ8zlMWEKeJ7kfdDR6AyuxsZexG5NyT3Iy4bJ3cwhZLO-6Y9OiDRJyNWjNK1ErW_qHp6DUwbPWR5tleg=='
    network_mode: host
