---
- name: Removing previous installation
  file:
    path: /docker-data/grafana
    state: absent
  tags:
    - grafana

- name: Stopping old container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: absent
  tags:
    - grafana

- name: adding Grafana group
  group:
    name: grafana
    gid: 472
    state: present
  tags:
    - grafana

- name: adding Grafana user
  user:
    name: grafana
    group: grafana
    create_home: no
    shell: /usr/bin/false
    uid: 472
    state: present
  tags:
    - grafana

- name: Creating directories to deploy
  file:
    path: /docker-data/grafana/etc
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags:
    - grafana

- name: Creating directories to deploy
  file:
    path: /docker-data/grafana/scripts
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags:
    - grafana

- name: Creating directories to deploy
  file:
    path: /docker-data/grafana/log
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags:
    - grafana

- name: Creating a temporary container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
  tags:
    - grafana

- name: Getting files from grafana container
  shell: |
    docker cp grafana:/etc/grafana/grafana.ini /docker-data/grafana/etc
    docker cp grafana:/usr/share/grafana/public/dashboards .
    docker cp grafana:/var/lib/grafana /docker-data/grafana/lib

    chown grafana.grafana lib
    exit 0
  args:
    chdir: /docker-data/grafana/
  tags:
    - grafana

- name: Waiting for grafana.ini is created
  shell: while [ ! -f /docker-data/grafana/etc/grafana.ini ]; do sleep 1; done
  tags:
    - grafana

- name: Changing permissions
  shell: |
    chown -R grafana.grafana *
    chmod 640 grafana.db
    chmod 755 plugins png

    exit 0
  args:
    chdir: /docker-data/grafana/lib
  tags:
    - grafana

- name: Stopping temporal container
  docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: absent
  tags:
    - grafana

- name: Adding URI path
  lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;root_url.*$'
    line: "root_url = {{ root_url }}"
    state: present
  tags:
    - grafana

- name: Enabling serving from subpath
  lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;serve_from_sub_path = false$'
    line: "serve_from_sub_path = {{ serve_from_sub_path }}"
    state: present
  tags:
    - grafana

- name: Changing default port to 3001
  lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;http_port = 3000$'
    line: "http_port = {{ http_port }}"
    state: present
  tags:
    - grafana

- name: Copying docker-compose
  template:
    src: docker-compose.yml
    dest: /docker-data/grafana/docker-compose.yml
    mode: '0644'
  tags:
    - grafana

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/grafana
    build: no
    pull: yes
  tags:
    - grafana
    