---
- name: Removing previous installation
  ansible.builtin.file:
    path: /docker-data/grafana
    state: absent
  tags:
    - grafana

- name: Stopping old container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: absent
  tags:
    - grafana

- name: Adding Grafana group
  ansible.builtin.group:
    name: grafana
    gid: 472
    state: present
  tags:
    - grafana

- name: Adding Grafana user
  ansible.builtin.user:
    name: grafana
    group: grafana
    create_home: false
    shell: /usr/bin/false
    uid: 472
    state: present
  tags:
    - grafana

- name: Creating directories to deploy
  ansible.builtin.file:
    path: /docker-data/grafana/etc
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags:
    - grafana

- name: Creating directories to deploy
  ansible.builtin.file:
    path: /docker-data/grafana/lib
    state: directory
    owner: grafana
    group: grafana
    mode: '0755'
  tags:
    - grafana

- name: Creating a temporary container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
  tags:
    - grafana

- name: "Getting files from grafana container"
  ansible.builtin.shell: |
    docker cp grafana:/etc/grafana/. etc
    docker cp grafana:/var/lib/grafana/. lib

    sudo touch lib/grafana.db
    sudo chown -R grafana.grafana *
    sudo chmod 640 lib/grafana.db

    while [ ! -f /docker-data/grafana/etc/grafana.ini ]; do sleep 1; done
  args:
    chdir: /docker-data/grafana/
  tags:
    - grafana

- name: Stopping temporal container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:latest
    state: absent
  tags:
    - grafana

- name: Adding URI path
  ansible.builtin.lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;root_url.*$'
    line: "root_url = {{ root_url }}"
    state: present
  tags:
    - grafana

- name: Enabling serving from subpath
  ansible.builtin.lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;serve_from_sub_path = false$'
    line: "serve_from_sub_path = {{ serve_from_sub_path }}"
    state: present
  tags:
    - grafana

- name: Changing default port
  ansible.builtin.lineinfile:
    path: /docker-data/grafana/etc/grafana.ini
    insertafter: '.*;http_port = 3000$'
    line: "http_port = {{ http_port }}"
    state: present
  tags:
    - grafana

- name: "Copying docker-compose"
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /docker-data/grafana/docker-compose.yml
    mode: '0644'
  tags:
    - grafana

- name: "Run docker-compose up"
  community.docker.docker_compose_v2:
    project_src: /docker-data/grafana
    build: never
    pull: missing
    state: present
  tags:
    - grafana

- name: Get information about the grafana container
  community.docker.docker_container_info:
    name: grafana
  register: grafana_container_info
  tags:
    - grafana

- name: Extract the IP address of the grafana service
  ansible.builtin.debug:
    msg: "Grafana Container IP address: {{ grafana_container_info.container.NetworkSettings.Networks.services.IPAddress }}"
  tags:
    - grafana

- name: Waiting for Grafana to start
  ansible.builtin.wait_for:
    host: "{{ grafana_container_info.container.NetworkSettings.Networks.services.IPAddress }}"
    port: 3000
    delay: 1
    sleep: 1
    timeout: 30
  tags:
    - grafana

- name: "Setting admin password"
  ansible.builtin.shell: |
    cd /docker-data/grafana
    docker compose exec grafana grafana-cli admin reset-admin-password {{ grafana_admin_password }}
  tags:
    - grafana
