version: "2"
services:
  duc:
    image: aanousakis/no-ip
    container_name: duc
    restart: unless-stopped
    environment: 
      - TZ="Europe/Madrid"
      - USERNAME=ymbihq
      - PASSWORD=%d8596wTJ3g4%lY1%3
      - DOMAINS=oriolrius.ddns.net
      - INTERVAL=5
