version: '3'
services:
  rproxy:
    container_name: rproxy
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    network_mode: host
    environment:
      DB_SQLITE_FILE: "{{ db_sqlite_file }}"
      DISABLE_IPV6: "{{ disable_ipv6|string|lower }}"
      TZ: "{{ timezone }}"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
