---
- name: Creating directories to deploy
  file:
    path: /docker-data/n8n/data
    state: directory
  tags:
    - n8n

- name: Copying docker-compose
  copy:
    src: docker-compose.yml
    dest: /docker-data/n8n/docker-compose.yml
    mode: '0644'
  tags:
    - n8n

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/n8n
    build: no
    pull: yes
  tags:
    - n8n
