---
- name: Stopping old container
  docker_container:
    name: n8n
    image: n8nio/n8n
    state: absent
  tags:
    - n8n

- name: Removing previous installation
  file:
    path: /docker-data/n8n
    state: absent
  tags:
    - n8n

- name: Creating directories to deploy
  file:
    path: /docker-data/n8n/data
    state: directory
    mode: '0755'
    owner: 1000
    group: 1000
  tags:
    - n8n

- name: Copying docker-compose
  template:
    src: docker-compose.yml
    dest: /docker-data/n8n/docker-compose.yml
    mode: '0644'
  tags:
    - n8n

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/n8n
    build: no
    pull: yes
  tags:
    - n8n
