---
- name: Creating directories to deploy
  file:
    path: /docker-data/rproxy/etc
    state: directory
    owner: 0
    group: 0
  tags:
    - rproxy

- name: Copying docker-compose
  copy:
    src: docker-compose.yml
    dest: /docker-data/rproxy/docker-compose.yml
    mode: '0644'
  tags:
    - rproxy

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/rproxy
    build: no
    pull: yes
  tags:
    - rproxy

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/rproxy
    build: no
    pull: yes
  tags:
    - rproxy