---
- name: Remove previous installation
  file:
    path: /docker-data/homer
    state: absent
  tags:
    - homer

- name: Stopping old container
  docker_container:
    name: homer
    image: b4bz/homer
    state: absent
  tags:
    - homer

- name: Creating directories to deploy
  file:
    path: /docker-data/homer/etc
    state: directory
    owner: 1000
    group: 100
    mode: '0755'
  tags:
    - homer

- name: Copying docker-compose
  copy:
    src: docker-compose.yml
    dest: /docker-data/homer/docker-compose.yml
    mode: '0644'
  tags:
    - homer

- name: Copying assets
  copy:
    src: assets
    dest: /docker-data/homer
    directory_mode: '0775'
    mode: '0664'
    owner: 1000
    group: 100
  tags:
    - homer

- name: Template of the main page
  template:
    src: config.yml
    dest: /docker-data/homer/assets/config.yml
  tags:
    - homer

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/homer
    build: no
    pull: yes
  tags:
    - homer
