version: '3.3'
services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - N8N_BASIC_AUTH_ACTIVE={{ true|string|lower }}
      - N8N_BASIC_AUTH_USER={{ n8n_basic_auth_user }}
      - N8N_BASIC_AUTH_PASSWORD={{ n8n_basic_auth_password }}
      - GENERIC_TIMEZONE={{ timezone }}
    volumes:
      - ./data:/home/node/.n8n
    network_mode: host