---
- name: Wait for apt to unlock
  become: true
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;
  tags:
    - docker

- name: Install docker dependencies
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common','python3-pip']
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add Docker s GPG key for ubuntu from official site
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Configure Docker for ubuntu stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release  }} stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker

- name: Check docker-ce is running
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: Get the latest release URL for docker-compose
  uri:
    url: "https://api.github.com/repos/docker/compose/releases/latest"
    return_content: yes
    status_code: 200
  register: release_url

- name: Latest docker-compose version
  debug:
    msg: "{{ release_url.json.tag_name }}"

- name: Download the docker-compose binary file
  get_url:
    url: "{{ release_url.json.assets | selectattr('name', 'match', 'docker-compose-linux-x86_64') | map(attribute='browser_download_url') | list | first }}"
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker

- name: Install Docker Module for Python
  pip:
    name: docker
  tags:
    - docker

- name: Install docker-compose Module for Python
  pip:
    name: docker-compose
  tags:
    - docker
