---
- name: Wait for apt to unlock
  become: yes
  shell:  while sudo fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 5; done;

- name: Install docker dependencies
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common','python3-pip']
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add Docker s GPG key for ubuntu from official site
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Verify gpg key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present
  tags:
    - docker

- name: Configure Docker for ubuntu stable repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
    state: present
    update_cache: yes
  tags:
    - docker

- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - docker

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: yes
  tags:
    - docker

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.10.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags:
    - docker

- name: Install Docker Module for Python
  pip:
    name: docker
  tags:
    - docker

- name: Install docker-compose Module for Python
  pip:
    name: docker-compose
  tags:
    - docker
