---
- name: Remove previous deployment
  file:
    path: /docker-data/nanomq
    state: absent
  tags:
    - nanomq

- name: Stopping old container
  docker_container:
    name: nanomq
    image: emqx/nanomq
    state: absent
  tags:
    - nanomq

- name: Creating directories to deploy
  file:
    path: /docker-data/nanomq/etc
    state: directory
    owner: 0
    group: 0
  tags:
    - nanomq

- name: Copying docker-compose
  copy:
    src: docker-compose.yml
    dest: /docker-data/nanomq/docker-compose.yml
    mode: '0644'
  tags:
    - nanomq

- name: Copying an empty config file
  copy:
    src: nanomq.conf
    dest: /docker-data/nanomq/etc/nanomq.conf
    mode: '0644'
  tags:
    - nanomq

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/nanomq
    build: no
    pull: yes
  tags:
    - nanomq

- name: Run docker-compose up
  docker_compose:
    project_src: /docker-data/nanomq
    build: no
    pull: yes
  tags:
    - nanomq