---
- name: Stopping old container
  ansible.builtin.docker_container:
    name: nanomq
    state: absent
  tags:
    - nanomq

- name: Remove previous deployment
  ansible.builtin.file:
    path: /docker-data/nanomq
    state: absent
  tags:
    - nanomq

- name: Creating directories to deploy
  ansible.builtin.file:
    path: /docker-data/nanomq/etc
    state: directory
    owner: 0
    group: 0
    mode: '0755'
  tags:
    - nanomq

- name: Copying docker-compose
  ansible.builtin.template:
    src: docker-compose.yml
    dest: /docker-data/nanomq/docker-compose.yml
    mode: '0644'
  tags:
    - nanomq

- name: Copying an empty config file
  ansible.builtin.copy:
    src: nanomq.conf
    dest: /docker-data/nanomq/etc/nanomq.conf
    mode: '0644'
  tags:
    - nanomq

- name: Templating ACL conf file
  ansible.builtin.template:
    src: nanomq_acl.conf.j2
    dest: /docker-data/nanomq/etc/nanomq_acl.conf
    mode: '0644'
  tags:
    - nanomq

- name: Templating password file
  ansible.builtin.template:
    src: nanomq_pwd.conf.j2
    dest: /docker-data/nanomq/etc/nanomq_pwd.conf
    mode: '0644'
  tags:
    - nanomq

- name: Run docker-compose up
  community.docker.docker_compose:
    project_src: /docker-data/nanomq
    build: no
    pull: yes
  tags:
    - nanomq
