galaxy_info:
  author: Oriol Rius
  role_name: install_docker
  description: 'Installing docker-ce on Ubuntu using ppa'
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - docker
    - sysadmin
    - ubuntu